### ISSUE TITLE
Depricate kube cronjob 

### ISSUE THREAD

**Issue by teng1** [UKHomeOffice/clamav-http#8]
Hi, 
Have noticed a few issues with kube cronjobs not scheduling or deadlines being missed (in general have found the resource unreliable).

 One approach which would remove the need for scheduling cronjob objects and having a dedicated cron container is to use the native `--checks` directive of freshclam to specify the number of checks per day in clamav-notify and then use `--on-update-execute` directive to run the script which patches the deployment. This would also allow for an atomic deployment using `helm install --atomic`  without needing to wait for the cronjob to run.

**Comment by ukho-cfreeman** [comment]
Hi Tom, i'm guessing this issue has been resolved? Reopen it if it hasn't
