### ISSUE TITLE
Add promethus endpoint

### ISSUE THREAD

**Issue by teng1** [UKHomeOffice/clamav-http#9]
Would be good to have a metrics endpoint for the clamav-notify / clamav scanning pods to help with monitoring the service. There are a fair few examples available which could be built on/PR'd, the endpoint ideally would hook into freshclam directives to monitor update operations / failures on the mirror (clamav-notify)

**Comment by ukho-cfreeman** [comment]
Hi @teng1 - looks like clamav-notify was removed, closing this issue
